version = 0.1
[default.deploy.parameters]
stack_name = "dashora-analytics"
resolve_s3 = true
s3_prefix = "dashora-analytics"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "JwtSecret=\"da5h0raAn4lyt1csS3cretK3y2024Pr0duct10n\""
