version = 0.1
[default.deploy.parameters]
stack_name = "dashora-api-backend"
resolve_s3 = true
s3_prefix = "dashora-api-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "JwtSecret=\"5pTdM7J83f2qzX9rKvWcYb4sNhG6A1uEjL0VQxZyPwRtB8DoFaHkIcSm\""
